[build]
  command = "yarn build"
  publish = "out"

[context.prod]
  command = "yarn build"
  publish = "out"
  environment = { NEXT_PUBLIC_CMS_URL="http://localhost:1337",NEXT_PUBLIC_API_URL="https://asia-south1-payorb-prod.cloudfunctions.net",NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyCXOsWI8rTwdM_mweNWT2f8slsmqGaf5pk",NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="payorb-prod.firebaseapp.com",NEXT_PUBLIC_FIREBASE_PROJECT_ID="payorb-prod",NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="payorb-prod.appspot.com",NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID="753115269023",NEXT_PUBLIC_FIREBASE_APP_ID="1:753115269023:web:26f9a74d58302c7d49dfaa",NEXT_PUBLIC_PAYMENT_GATEWAY_KEY="rzp_live_DpNBVgsAwqessX",NEXT_PUBLIC_GOOGLE_ANALYTICS="G-ZKNL3ZEK44"}

[context.main]
  command = "yarn build"
  publish = "out"
  environment = { NEXT_PUBLIC_CMS_URL="http://localhost:1337",NEXT_PUBLIC_API_URL="https://asia-south1-payorb-staging.cloudfunctions.net",NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyATler-IHGoMPozwtjsPVu3dXiJ2AcLM44",NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="payorb-staging.firebaseapp.com",NEXT_PUBLIC_FIREBASE_PROJECT_ID="payorb-staging",NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="payorb-staging.appspot.com",NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID="775767066439",NEXT_PUBLIC_FIREBASE_APP_ID="1:775767066439:web:ebbd0ab42264bb858d6e62",NEXT_PUBLIC_PAYMENT_GATEWAY_KEY="rzp_test_fA0gdYKhk4xUou" }


[[plugins]]
  package = "@netlify/plugin-nextjs"
