[build]
  command = "yarn build"
  publish = "out"

[context.prod]
  command = "yarn build"
  publish = "out"
  environment = { NEXT_PUBLIC_CMS_URL="http://localhost:1337",NEXT_PUBLIC_API_URL="https://us-central1-payorb-92ef0.cloudfunctions.net",NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyBCqsdKA3kx8zn87k92gz4a04LFSQ82rr0",NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="payorb-92ef0.firebaseapp.com",NEXT_PUBLIC_FIREBASE_PROJECT_ID="payorb-92ef0",NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="payorb-92ef0.appspot.com",NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID="1087459324541",NEXT_PUBLIC_FIREBASE_APP_ID="1:1087459324541:web:0a6e0ad769ae109eaaf714",NEXT_PUBLIC_PAYMENT_GATEWAY_KEY="rzp_live_DpNBVgsAwqessX",NEXT_PUBLIC_GOOGLE_ANALYTICS="G-NMEE2S9MQ9"}

[context.main]
  command = "yarn build"
  publish = "out"
  environment = { NEXT_PUBLIC_CMS_URL="http://localhost:1337",NEXT_PUBLIC_API_URL="https://asia-south1-payorb-staging.cloudfunctions.net",NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyATler-IHGoMPozwtjsPVu3dXiJ2AcLM44",NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="payorb-staging.firebaseapp.com",NEXT_PUBLIC_FIREBASE_PROJECT_ID="payorb-staging",NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="payorb-staging.appspot.com",NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID="775767066439",NEXT_PUBLIC_FIREBASE_APP_ID="1:775767066439:web:ebbd0ab42264bb858d6e62",NEXT_PUBLIC_PAYMENT_GATEWAY_KEY="rzp_test_fA0gdYKhk4xUou" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
