export const PAGE_PATHS = {
  SIGNUP: "/signup",
  SIGNIN: "/signin",
  LANDING: "/",
  VENDOR: "/vendor",
  VENDOR_DASHBOARD_PROFILE: "/vendor/profile",
  VENDOR_DASHBOARD_EVENTS: "/vendor/events",
  VENDOR_DASHBOARD_FINANCIALS: "/vendor/financials",
  VENDOR_DASHBOARD_CUSTOMERS: "/vendor/customers",
  VENDOR_DASHBOARD_CREATE_EVENT: "/vendor/events/create",
  VENDOR_DASHBOARD_EDIT_EVENT: "/vendor/events/edit",
  CUSTOMER_EVENTS: "/customers/events",
  CUSTOMER_EVENTS_REGISTER: "/customers/events/register",
  CUSTOMER_EVENTS_REVIEW: "/customers/events/review",
  CUSTOMER_VENDOR_VIEW: "/customers/vendor",
  POLICY_TERMS_AND_CONDS: "/policies/terms-conditions",
  POLICY_PRIVACY: "/policies/privacy",
  POLICY_WEB_DISCLAMER: "/policies/web-disclaimer",
  POLICY_USER_AGREE: "/policies/user-agreement",
  POLICIES: "/policies"
};
